# Generated by Django 4.2.27 on 2026-01-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='img/domyslny_avatar.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
